services:
  mongodb:
    image: mongo:7
    container_name: foodora-mongodb
    ports:
      - "27017:27017"

  backend:
    image: food_delevery-backend:latest
    container_name: foodora-backend
    environment:
      MONGODB_URI: mongodb://foodora-mongodb:27017/food_delivery
    ports:
      - "5000:5000"

  frontend:
    image: food_delevery-frontend:latest
    container_name: foodora-frontend
    ports:
      - "3000:80"